name: Deploy Xomcloud Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Retrieve SSM Parameters
        run: |
          echo "SOUNDCLOUD_CLIENT_ID=$(aws ssm get-parameter --name "/xomcloud/soundcloud/CLIENT_ID" --with-decryption --query "Parameter.Value" --output text)" >> soundcloud_credentials.env
          echo "SOUNDCLOUD_CLIENT_SECRET=$(aws ssm get-parameter --name "/xomcloud/soundcloud/CLIENT_SECRET" --with-decryption --query "Parameter.Value" --output text)" >> soundcloud_credentials.env
          # echo "API_AUTH_TOKEN=$(aws ssm get-parameter --name "/xomcloud/api/API_AUTH_TOKEN" --with-decryption --query "Parameter.Value" --output text)" >> soundcloud_credentials.env
          # echo "API_ID=$(aws ssm get-parameter --name "/xomcloud/api/API_ID" --with-decryption --query "Parameter.Value" --output text)" >> soundcloud_credentials.env
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Mask sensitive values
        run: |
          echo "::add-mask::$(grep 'SOUNDCLOUD_CLIENT_ID' soundcloud_credentials.env | cut -d'=' -f2)"
          echo "::add-mask::$(grep 'SOUNDCLOUD_CLIENT_SECRET' soundcloud_credentials.env | cut -d'=' -f2)"
          # echo "::add-mask::$(grep 'API_AUTH_TOKEN' soundcloud_credentials.env | cut -d'=' -f2)"
          # echo "::add-mask::$(grep 'API_ID' soundcloud_credentials.env | cut -d'=' -f2)"

      - name: Install dependencies
        run: npm install

      - name: Inject environment variables into Angular
        run: |
          # Replace placeholders in environment.ts
          sed -i "s|soundcloudClientId: '---'|soundcloudClientId: '$(grep 'SOUNDCLOUD_CLIENT_ID' soundcloud_credentials.env | cut -d'=' -f2)'|g" src/environments/environment.ts
          sed -i "s|soundcloudClientSecret: '---'|soundcloudClientSecret: '$(grep 'SOUNDCLOUD_CLIENT_SECRET' soundcloud_credentials.env | cut -d'=' -f2)'|g" src/environments/environment.ts
          # sed -i "s|apiAuthToken: '---'|apiAuthToken: '$(grep 'API_AUTH_TOKEN' soundcloud_credentials.env | cut -d'=' -f2)'|g" src/environments/environment.ts
          # sed -i "s|apiId: '---'|apiId: '$(grep 'API_ID' soundcloud_credentials.env | cut -d'=' -f2)'|g" src/environments/environment.ts
          # Set production flag
          sed -i "s|production: false|production: true|g" src/environments/environment.ts
          # Update callback URL for production
          sed -i "s|baseCallbackUrl: 'http://localhost:4200'|baseCallbackUrl: 'https://xomcloud.com'|g" src/environments/environment.ts

      - name: Build the project
        run: npm run build -- --configuration production

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          aws s3 sync ./dist/xomcloud s3://xomcloud.com --delete
